language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.0

    # The SDK version used to compile your project
    - android-23

  # White list of SDK licenses to be accepted.
  licenses:
    - 'android-sdk-license-.+'
    - 'android-sdk-preview-license-.+'
